### ISSUE TITLE
Mod unable to load due to java.lang.EceptionInInitializerError: null

### ISSUE THREAD

**Issue by Frosticle** [luccaPossamai/optical#6] opened 2024-06-10 12:27 UTC
Got this error when loading up the game. Not sure if this could be compat issue. Mod list should be in the log file.

Log : 
[latest.log](https://github.com/user-attachments/files/15766040/latest.log)

Images :
[Screenshot 2024-06-10 202044](https://github.com/luccaPossamai/optical/assets/43837518/d0006f49-0127-41b1-957e-9fd6562d5011)

**Comment by luccaPossamai** [comment] 2024-06-18 17:53
It's probably a compatibility issue, I guess you already tried to remove the optical mod and run the game to check if the problem is really with optical. The log mentions about trying to fire events and fail for the optical mod. I'll see more about that eventually, for now, I know that flywheel can create a lot of compatibilty issues, then if you really want this mod you can search for more about that.

**Comment by Frosticle** [comment] 2024-06-19 01:31
I tried it with another modpack i play with and it runs fine, no error during startup. I guess I'll try to find the incompatible mod later.

**Comment by luccaPossamai** [comment] 2024-06-19 17:24
I'm working on get rid of the bugs that were found, if you manage to find the mods that are incompatible with optical please send me a message, that would help me a lot. That idea of vertical beams was the most suggested idea I'm trying to implement it in the next version.

**Comment by Frosticle** [comment] 2024-06-23 14:22
Huh, I was playing with my current modpack and it randomly crashed with this error again. I restarted the game and it didn't show again. Crash report below.

[crash-2024-06-23_22.14.27-fml.txt](https://github.com/user-attachments/files/15944985/crash-2024-06-23_22.14.27-fml.txt)

**Comment by Frosticle** [comment] 2024-06-23 14:28
I checked the previous crash reports and it seems to be the same error happening.

**Comment by luccaPossamai** [comment] 2024-07-03 20:17
Oh, I see. I'll try to fix this. Maybe there's a well defined order to register partial models. Something that I did not realize that could happen until now. Thank you very much.

**Comment by SPAZ97** [comment] 2024-07-22 21:45
Hey sorry for digging up skeletons like this but I had this exact same issue and I did some testing and found out the mod causing the error. Do you have ModernFix installed? If so, that's the problem.

**Comment by luccaPossamai** [comment] 2024-07-23 00:17
Thanks for your contribution. It's not expected this incompatibility with ModernFix, I was trying to solve this problem, I think that in newer versions it's fixed. Versions only available in git repository. When its time to test the updates I'll close this issue if fixed.

**Closed** 2024-09-23 20:18 UTC
